# Generated by Django 5.0.7 on 2024-07-23 17:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Predication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', models.FileField(help_text='Please record voice [15sec-45sec] voice must be .wmv format', upload_to='audios/')),
                ('mdvp_fo', models.IntegerField(default=0, help_text='Average Vocal Fundamental Frequency')),
                ('mdvp_fhi', models.IntegerField(default=0, help_text='Minimum Vocal Fundamental Frequency')),
                ('mdvp_flo', models.IntegerField(default=0, help_text='Maximum Vocal Fundamental Frequency')),
                ('mdvp_shimmer', models.IntegerField(default=0)),
                ('mdvp_jitter', models.IntegerField(default=0)),
                ('rpde', models.IntegerField(default=0)),
                ('d2', models.IntegerField(default=0)),
                ('nhr', models.IntegerField(default=0)),
                ('hnr', models.IntegerField(default=0)),
                ('dfa', models.IntegerField(default=0)),
                ('ppe', models.IntegerField(default=0)),
                ('spread1', models.IntegerField(default=0)),
                ('spread2', models.IntegerField(default=0)),
                ('status', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
